Cursa/Controllers/SubProjectsController.cs
using System;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using AutoMapper;
using Cursa.ViewModels.SubProjectVM;
using DataLayer;
using DataLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Cursa.Controllers
{
    [Authorize(Roles = "Менеджер")]
    public class SubProjectsController : Controller
    {
        private readonly EfDbContext _context;
        private readonly IMapper _mapper;
        private readonly ILogger<SubProjectsController> _logger;

        public SubProjectsController(EfDbContext context, IMapper mapper, ILogger<SubProjectsController> logger)
        {
            _context = context;
            _mapper = mapper;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> GetSubProject(int? projectId)
        {
            if (projectId == null)
            {
                return NotFound();
            }

            var result =
                await _context.Projects.FirstOrDefaultAsync(p =>
                    p.Id == projectId);
            if (result == null)
            {
                return NotFound();
            }

            return View(new SubProjectComplexDisplayViewModel
            {
                ProjectId = result.Id,
                ProjectName = result.Name
            });
        }

        [HttpPost]
        public IActionResult FindSubProjects()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request
                    .Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchGlobalValue = Request.Form["search[value]"].FirstOrDefault();
                var searchNameValue = Request.Form["columns[1][search][value]"].FirstOrDefault();
                var searchCodeValue = Request.Form["columns[2][search][value]"].FirstOrDefault();
                var searchEmployeeValue = Request.Form["columns[3][search][value]"].FirstOrDefault();
                var searchStatusValue = Request.Form["columns[4][search][value]"].FirstOrDefault();
                var searchContractValue = Request.Form["columns[5][search][value]"].FirstOrDefault();
                var pageSize = length != null ? Convert.ToInt32(length) : 0;
                var skip = start != null ? Convert.ToInt32(start) : 0;
                var id = Request.Form["projectId"].FirstOrDefault();
                int projectId = id != null ? Convert.ToInt32(id) : 0;

                var projectsData = _mapper.ProjectTo<SubProjectsDisplayViewModel>(
                    _context.SubProjects
                        .AsNoTracking()
                        .Where(subProject => subProject.ProjectId == projectId));
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    projectsData = projectsData.OrderBy(sortColumn + " " + sortColumnDirection);
                }

                if (!string.IsNullOrEmpty(searchGlobalValue))
                {
                    projectsData = projectsData.Where(m => m.Name.Contains(searchGlobalValue)
                                                           || m.Code.Contains(searchGlobalValue)
                                                           || m.Employee.FullName.Contains(searchGlobalValue)
                                                           || m.StatusName.Contains(searchGlobalValue)
                                                           || m.Contract.Contains(searchGlobalValue));
                }

                if (!string.IsNullOrEmpty(searchNameValue))
                {
                    projectsData = projectsData.Where(m => m.Name.Contains(searchNameValue));
                }

                if (!string.IsNullOrEmpty(searchCodeValue))
                {
                    projectsData = projectsData.Where(m => m.Code.Contains(searchCodeValue));
                }

                if (!string.IsNullOrEmpty(searchEmployeeValue))
                {
                    projectsData = projectsData.Where(m => m.Employee.FullName.Contains(searchEmployeeValue));
                }

                if (!string.IsNullOrEmpty(searchStatusValue))
                {
                    projectsData = projectsData.Where(m => m.StatusName.Contains(searchStatusValue));
                }

                if (!string.IsNullOrEmpty(searchContractValue))
                {
                    projectsData = projectsData.Where(m => m.Contract.Contains(searchContractValue));
                }

                var recordsTotal = projectsData.Count();
                var data = projectsData.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                    {draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data};
                return Ok(jsonData);
            }
            catch (Exception e)
            {
                _logger.LogError("Error search:{ExceptionMessage}", e.Message);
                return NotFound();
            }
        }

        // GET: SubProjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subProject = await _context.SubProjects
                .Include(s => s.Employee)
                .Include(s => s.Project)
                .Include(s => s.Status)
                .Include(p => p.ModifiedUser)
                .Include(p => p.CreatedUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subProject == null)
            {
                return NotFound();
            }

            return View(subProject);
        }

        // GET: SubProjects/Create/7
        public IActionResult Create(int? projectId)
        {
            if (projectId == null)
            {
                return NotFound();
            }

            var project = _context.Projects.FirstOrDefault(p => p.Id == projectId);
            if (project == null)
            {
                return NotFound();
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees
                .Where(x => x.Department.IsResponsibleProjectsAndSubProjects), "Id", "GetFullName");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name");
            ViewData["ContractorId"] = new SelectList(_context.Contractors, "Id", "Name");
            ViewBag.TitleProject = "для проекта: " + project.Name;
            return View(new SubProjectCreateEditViewModel
            {
                ProjectId = (int) projectId
            });
        }

        // POST: SubProjects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("ProjectId,Name,Code,EmployeeId,StatusId,Contract,ContractorId,Description,EndDate")]
            SubProjectCreateEditViewModel subProjectDTO)
        {
            if (ModelState.IsValid)
            {
                var subProject = _mapper.Map<SubProjectCreateEditViewModel, SubProject>(subProjectDTO);
                _context.Add(subProject);
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(GetSubProject), new {projectId = subProjectDTO.ProjectId});
                }
                catch (DbUpdateException e)
                {
                    var exception = e.InnerException;
                    if (exception != null && exception.Message.Contains("IX_SubProjects_Name"))
                    {
                        ModelState.AddModelError("Name", "Подпроект уже существует");
                    }

                    if (exception != null && exception.Message.Contains("IX_SubProjects_Code"))
                    {
                        ModelState.AddModelError("Code", "Такой код уже используется");
                    }
                }
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees
                .Where(x => x.Department.IsResponsibleProjectsAndSubProjects), "Id", "GetFullName");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name");
            ViewData["ContractorId"] = new SelectList(_context.Contractors, "Id", "Name");
            return View(subProjectDTO);
        }

        // GET: SubProjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subProject = await _context.SubProjects.FindAsync(id);
            var subProjectDTO = _mapper.Map<SubProject, SubProjectCreateEditViewModel>(subProject);
            if (subProject == null)
            {
                return NotFound();
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees
                .Where(x => x.Department.IsResponsibleProjectsAndSubProjects), "Id", "GetFullName");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name");
            ViewData["ContractorId"] = new SelectList(_context.Contractors, "Id", "Name", subProject.ContractorId);
            return View(subProjectDTO);
        }

        // POST: SubProjects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,

Cursa/Views/SubProjects/Create.cshtml
@model Cursa.ViewModels.SubProjectVM.SubProjectCreateEditViewModel

@{
    ViewData["Title"] = "Создать подпроект";
}
<style type="text/css">.control-label { }</style>

<h4>@ViewData["Title"] @ViewBag.TitleProject</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProjectId"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control"/>
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ContractorId" class="control-label"></label>
                <select asp-for="ContractorId" class="form-control" asp-items="ViewBag.ContractorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Contract" class="control-label"></label>
                <input asp-for="Contract" class="form-control"/>
                <span asp-validation-for="Contract" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control"/>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="SubProjects" asp-action="GetSubProject" asp-route-projectId="@Model.ProjectId">Назад</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Cursa/Views/SubProjects/Delete.cshtml
@model DataLayer.Entities.SubProject

@{
    ViewData["Title"] = "Удаление подпроекта";
}

<h4>@ViewData["Title"]</h4>

<h6 style="color:red">Подтвердите удаление</h6>
<div>
   <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a  asp-action="GetSubProject" asp-route-projectId="@Model.ProjectId">Назад</a>
    </form>
</div>

Cursa/Views/SubProjects/Details.cshtml
@model DataLayer.Entities.SubProject

@{
    ViewData["Title"] = "О подпрокте";
}

<h4>@ViewData["Title"]</h4>

<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.GetFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contract)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contract)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedUser):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedUser.GetFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedUser):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedUser.GetFullName)
        </dd>
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> | *@
    @* <a asp-action="Index">Back to List</a> *@


    <a href="/SubProjects/GetSubProject?projectId=@Model.ProjectId">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
        </svg>
    </a>&nbsp; &nbsp; &nbsp;
    <a href="/SubProjects/Edit?id=@Model.Id">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            \n' +
            // ' <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>\n' +
            // '
        </svg>
    </a>&nbsp; &nbsp; &nbsp;
    <a href="/SubProjects/Delete?id=@Model.Id">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
    </a>
</div>

Cursa/Views/SubProjects/Edit.cshtml
@model Cursa.ViewModels.SubProjectVM.SubProjectCreateEditViewModel

@{
    ViewData["Title"] = "Редактирование записи подпроекта";
}

<h4>@ViewData["Title"]</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="ProjectId"/>
            @* <div class="form-group"> *@
            @*     <label asp-for="ProjectId" class="control-label"></label> *@
            @*     <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select> *@
            @*     <span asp-validation-for="ProjectId" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control"/>
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractorId" class="control-label"></label>
                <select asp-for="ContractorId" class="form-control" asp-items="ViewBag.ContractorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Contract" class="control-label"></label>
                <input asp-for="Contract" class="form-control"/>
                <span asp-validation-for="Contract" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control"/>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="SubProjects" asp-action="GetSubProject" asp-route-projectId="@Model.ProjectId">Вернуться к проектам</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Cursa/Views/SubProjects/GetSubProject.cshtml
@model Cursa.ViewModels.SubProjectVM.SubProjectComplexDisplayViewModel

@{
    ViewData["Title"] = "Подпроекты для проекта: ";
}

<h4>@ViewData["Title"] @Model.ProjectName</h4>

<p>
    <a asp-action="Create" asp-route-projectId="@Model.ProjectId">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>Добавить
    </a>
</p>
<table id="subprojectDatatable" class="table" style="width:100%" >
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.Employee.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.StatusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.Contract)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubProjectVM.EndDate)
        </th>

        <th>
        </th>
    </tr>
    </thead>
    <tbody></tbody>
    <tfoot>
    <tr>
        <th>
        </th>
        <th class="search">
            @Html.DisplayNameFor(model => model.SubProjectVM.Name)
        </th>
        <th class="search">
            @Html.DisplayNameFor(model => model.SubProjectVM.Code)
        </th>
        <th class="search">
            @Html.DisplayNameFor(model => model.SubProjectVM.Employee.FullName)
        </th>
        <th class="search">
            @Html.DisplayNameFor(model => model.SubProjectVM.StatusName)
        </th>
        <th class="search">
            @Html.DisplayNameFor(model => model.SubProjectVM.Contract)
        </th>
        <th>

        </th>
        <th>

        </th>
        <th>
        </th>
    </tr>
    </tfoot>
</table>
<script>
        let projectId=@Model.ProjectId;
</script>

@section Scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/moment.js/moment.js"></script>
    <script src="~/js/subprojectDatatable.js"></script>
}

<style>
   div.dataTables_wrapper {
          /* width: 1350px;*/
           margin: 0 auto;
       }
       @@media (min-width: 1000px) {
                div.dataTables_wrapper {
                   min-width: 1300px;
               }
           }
           
           @@media (max-width: 1000px) {
                div.dataTables_wrapper {
                   min-width: 900px;
               }
           }
        th, td { white-space: nowrap; }
    .in_progress {
        background-color: #20c99750;
    }
</style>

Cursa/Views/SubProjects/GetSubProjectById.cshtml
@model IEnumerable<DataLayer.Entities.SubProject>

@{
    ViewData["Title"] = "Подпроекты для проекта: ";
}

<h4>@ViewData["Title"] @ViewBag.ProjectName</h4>

<p>
    <a asp-controller="SubProjects" asp-action="Create" asp-route-projectId="@ViewBag.ProjectId">Создать</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>