Cursa/Controllers/DepartmentsController.cs
using System;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using AutoMapper;
using Cursa.ViewModels.DepartmentVM;
using DataLayer;
using DataLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace Cursa.Controllers
{
    [Authorize(Roles = "Менеджер")]
    public class DepartmentsController : Controller
    {
        private readonly EfDbContext _context;
        private readonly IMapper _mapper;
        private readonly ILogger<DepartmentsController> _logger;

        public DepartmentsController(EfDbContext context, IMapper mapper, ILogger<DepartmentsController> logger)
        {
            _context = context;
            _mapper = mapper;
            _logger = logger;
        }

        // GET: Departments
        public IActionResult Index() => View(new DepartmentDisplayViewModel());

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        [HttpPost]
        public IActionResult GetDepartments()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request
                    .Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchGlobalValue = Request.Form["search[value]"].FirstOrDefault();
                var pageSize = length != null ? Convert.ToInt32(length) : 0;
                var skip = start != null ? Convert.ToInt32(start) : 0;

                var projectsData = _mapper.ProjectTo<DepartmentDisplayViewModel>(_context.Departments
                    .AsNoTracking());

                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    projectsData = projectsData.OrderBy(sortColumn + " " + sortColumnDirection);
                }

                if (!string.IsNullOrEmpty(searchGlobalValue))
                {
                    projectsData = projectsData.Where(m => m.Name.Contains(searchGlobalValue));
                }

                var recordsTotal = projectsData.Count();
                var data = projectsData.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                    {draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data};
                return Ok(jsonData);
            }
            catch (Exception e)
            {
                _logger.LogError("Error search:{ExceptionMessage}", e.Message);
                return NotFound();
            }
        }

        // GET: Departments/Create
        public IActionResult Create() => View();

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,IsResponsibleProjectsAndSubProjects,IsResponsibleDesignWork")]
            Department department)
        {
            //IX_Departments_Name
            if (ModelState.IsValid)
            {
                if (_context.Departments.Any(x => String.Equals(x.Name, department.Name)))
                {
                    ModelState.AddModelError("Name", "Отдел уже существует");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Add(department);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateException e)
                    {
                        var exception = e.InnerException;
                        if (exception != null && exception.Message.Contains("IX_Departments_Name"))
                        {
                            ModelState.AddModelError("Name", "Отдел уже существует");
                        }
                    }
                }
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,IsResponsibleProjectsAndSubProjects,IsResponsibleDesignWork")]
            Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException e)
                {
                    var exception = e.InnerException;
                    if (exception != null && exception.Message.Contains("IX_Departments_Name"))
                    {
                        ModelState.AddModelError("Name", "Отдел уже существует");
                    }
                }
            }

            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Departments.FindAsync(id);

            if (department == null)
            {
                return NotFound();
            }
            try
                {
                    _context.Departments.Remove(department);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException e)
                {
                    _logger.LogInformation("{ExceptionMessage}", e.Message);
                    ModelState.AddModelError(String.Empty, "Невозможно удалить, на данный отдел имеются ссылки");
                }

            return View(department);
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.Id == id);
        }
    }
}

Cursa/Views/Departments/Create.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Создание";
}


<h4>Создать отдел</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsResponsibleProjectsAndSubProjects"/> @Html.DisplayNameFor(model => model.IsResponsibleProjectsAndSubProjects)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsResponsibleDesignWork"/> @Html.DisplayNameFor(model => model.IsResponsibleDesignWork)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">К списку отделов</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Cursa/Views/Departments/Delete.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Удаление отдела";
}

<h4>@ViewData["Title"]</h4>

<h6 style="color:red">Подтвердите удаление</h6>
<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsResponsibleProjectsAndSubProjects)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsResponsibleProjectsAndSubProjects)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsResponsibleDesignWork)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsResponsibleDesignWork)
        </dd>
        @* <dt class="col-sm-2"> *@
        @*     @Html.DisplayNameFor(model => model.CreatedDate) *@
        @* </dt> *@
        @* <dd class="col-sm-10"> *@
        @*     @Html.DisplayFor(model => model.CreatedDate) *@
        @* </dd> *@
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Удалить" class="btn btn-danger"/> |
        <a asp-action="Index">К списку отделов</a>
    </form>
</div>

Cursa/Views/Departments/Details.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Об отделе";
}

<h4>@ViewData["Title"]</h4>
<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsResponsibleProjectsAndSubProjects)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsResponsibleProjectsAndSubProjects)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsResponsibleDesignWork)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsResponsibleDesignWork)
        </dd>
        @* <dt class="col-sm-2"> *@
        @*     @Html.DisplayNameFor(model => model.CreatedDate) *@
        @* </dt> *@
        @* <dd class="col-sm-10"> *@
        @*     @Html.DisplayFor(model => model.CreatedDate) *@
        @* </dd> *@
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> | *@
    @* <a asp-action="Index">К списку отделов</a> *@

    <a href="/Departments/Index/">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
        </svg>
    </a>&nbsp; &nbsp; &nbsp;
    <a href="/Departments/Edit?id=@Model.Id">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            \n' +
            // ' <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>\n' +
            // '
        </svg>
    </a>&nbsp; &nbsp; &nbsp;
    <a href="/Departments/Delete?id=@Model.Id">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
    </a>
</div>

Cursa/Views/Departments/Edit.cshtml
@model DataLayer.Entities.Department

@{
    ViewData["Title"] = "Редактирование записи отдела";
}

<h4>@ViewData["Title"]</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsResponsibleProjectsAndSubProjects"/> @Html.DisplayNameFor(model => model.IsResponsibleProjectsAndSubProjects)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsResponsibleDesignWork"/> @Html.DisplayNameFor(model => model.IsResponsibleDesignWork)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @* <input type="hidden" asp-for="CreatedDate" class="form-control"/> *@

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">К списку отделов</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Cursa/Views/Departments/Index.cshtml
@model Cursa.ViewModels.DepartmentVM.DepartmentDisplayViewModel

@{
    ViewData["Title"] = "Отделы";
}

<h4>@ViewData["Title"]</h4>

<p>
    <a asp-controller="Departments" asp-action="Create">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>Добавить
    </a>
</p>
<table id="departmentDatatable" class="table">
    <thead>
    <tr>
         <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @* <th> *@
        @*     @Html.DisplayNameFor(model => model.Description) *@
        @* </th> *@
        @* <th> *@
        @*     @Html.DisplayNameFor(model => model.CreatedDate) *@
        @* </th> *@
        <th></th>
    </tr>
    </thead>
    @* <tbody> *@
    @* @foreach (var item in Model) *@
    @* { *@
    @*     <tr> *@
    @*         <td> *@
    @*             @Html.DisplayFor(modelItem => item.Name) *@
    @*         </td> *@
    @*         <td> *@
    @*             @Html.DisplayFor(modelItem => item.Description) *@
    @*         </td> *@
    @*         <td> *@
    @*             @Html.DisplayFor(modelItem => item.CreatedDate) *@
    @*         </td> *@
    @*         <td> *@
    @*             <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
    @*             <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
    @*             <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
    @*         </td> *@
    @*     </tr> *@
    @* } *@
    @* </tbody> *@
</table>
@section Scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/departmentDatatable.js"></script>
}