Cursa/Controllers/OrderCardsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using AutoMapper;
using Cursa.ViewModels.Base;
using Cursa.ViewModels.OrderCardVM;
using Cursa.ViewModels.ProductsVM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using DataLayer.Entities;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;

namespace Cursa.Controllers
{
    [Authorize(Roles = "Менеджер")]
    public class OrderCardsController : Controller
    {
        private readonly EfDbContext _context;
        private readonly IMapper _mapper;
        private readonly ILogger<OrderCardsController> _logger;

        public OrderCardsController(EfDbContext context, IMapper mapper, ILogger<OrderCardsController> logger)
        {
            _context = context;
            _mapper = mapper;
            _logger = logger;
        }

        // GET: OrderCards
        // public async Task<IActionResult> Index()
        // {
        //     var efDbContext = _context.OrderCards.Include(o => o.CreatedUser).Include(o => o.ModifiedUser)
        //         .Include(o => o.Product);
        //     return View(await efDbContext.ToListAsync());
        // }

        // GET: OrderCards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderCard = await _context.OrderCards
                .Include(o => o.Employee)
                .Include(o => o.CreatedUser)
                .Include(o => o.ModifiedUser)
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderCard == null)
            {
                return NotFound();
            }

            return View(orderCard);
        }

        [HttpGet]
        public IActionResult GetOrderCardsForProduct(int? productId)
        {
            if (productId == null)
            {
                return NotFound();
            }

            var product = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (product == null)
            {
                return NotFound();
            }

            return View(new OrderCardDisplayViewModel()
            {
                Product = new BaseViewModel()
                {
                    Id = product.Id,
                    Name = product.Name
                }
            });
        }

        [HttpPost]
        public IActionResult FindCardOrdersForProduct()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request
                    .Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchGlobalValue = Request.Form["search[value]"].FirstOrDefault();
                var pageSize = length != null ? Convert.ToInt32(length) : 0;
                var skip = start != null ? Convert.ToInt32(start) : 0;
                var id = Request.Form["productId"].FirstOrDefault();
                var productId = id != null ? Convert.ToInt32(id) : 0;

                var projectsData = _mapper.ProjectTo<OrderCardDisplayViewModel>(_context.OrderCards
                    .Include(x => x.Employee)
                    .AsNoTracking()
                    .Where(p => p.ProductId == productId));

                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    projectsData = projectsData.OrderBy(sortColumn + " " + sortColumnDirection);
                }

                if (!string.IsNullOrEmpty(searchGlobalValue))
                {
                    projectsData = projectsData.Where(m => m.Name.Contains(searchGlobalValue)
                                                           || m.Number.Contains(searchGlobalValue));
                }

                var recordsTotal = projectsData.Count();
                var data = projectsData.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                    {draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data};
                return Ok(jsonData);
            }
            catch (Exception e)
            {
                _logger.LogError("Error search:{ExceptionMessage}", e.Message);
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult GetCardOrdersItems()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request
                    .Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchGlobalValue = Request.Form["search[value]"].FirstOrDefault();
                // var searchNameValue = Request.Form["columns[2][search][value]"].FirstOrDefault();
                // var searchSerialNumValue = Request.Form["columns[3][search][value]"].FirstOrDefault();
                // var searchCertifiedNumValue = Request.Form["columns[4][search][value]"].FirstOrDefault();
                var pageSize = length != null ? Convert.ToInt32(length) : 0;
                var skip = start != null ? Convert.ToInt32(start) : 0;
                var id = Request.Form["OrderCardId"].FirstOrDefault();
                var orderCardId = id != null ? Convert.ToInt32(id) : 0;

                var projectsData = _context.Modules
                    .AsNoTracking()
                    .Include(x => x.ModuleType)
                    .Where(x => x.DestinationOrderCardId == orderCardId)
                    .ToList()
                    .GroupBy(x => x.ModuleType.Name)
                    .Select(x => new OrderCardSummaryModule
                    {
                        ModuleTypeName = x.Key,
                        Addresses = x.Select(m => m.DestinationPlace)
                    });

                var recordsTotal = projectsData.Count();
                var data = projectsData.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                    {draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data};
                return Ok(jsonData);
            }
            catch (Exception e)
            {
                _logger.LogError("Error search:{ExceptionMessage}", e.Message);
                return NotFound();
            }
        }

        // GET: OrderCards/Create
        public async Task<IActionResult> Create(int? productId)
        {
            if (productId == null)
            {
                return NotFound();
            }

            var product = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (product == null)
            {
                return NotFound();
            }

            ViewBag.TitleProduct = "для : " + product.Name;
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            var systemUnit =
                await _context.ModulesTypes.FirstOrDefaultAsync(x => x.IsActiv && !x.IsCommunicationDevice);
            if (systemUnit == null)
            {
                ModelState.AddModelError("", "Отсутствуют системные модули");
                return View(new OrderCardCreateEditVM()
                {
                    ProductId = product.Id
                });
            }


            int addressLength = systemUnit.NumberConnectionPoints;

            var modules = _context.ModulesTypes
                .Where(x => x.IsActiv && x.IsCommunicationDevice)
                .Select(x => new OrderCardCreateEditModuleVM()
                    {Id = x.Id, Name = x.Name, Addresses = new bool[addressLength]})
                .ToList();
            ViewData["EmployeeId"] = new SelectList(_context.Employees
                .Where(x => x.Department.IsResponsibleDesignWork), "Id", "GetFullName");
            return View(new OrderCardCreateEditVM()
            {
                ProductId = product.Id,
                systemUnit = new BaseViewModel()
                {
                    Id = systemUnit.Id,
                    Name = systemUnit.Name
                },
                ModulesVM = modules
            });
        }

        // POST: OrderCards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken] //[Bind("Name,Number,Path,ProductId,Id")]
        public async Task<IActionResult> Create([FromForm] OrderCardCreateEditVM orderCardVM)
        {
            if (ModelState.IsValid)
            {
                if (orderCardVM.ModulesVM != null && orderCardVM.systemUnit != null)
                {
                    var selectedModuleTypes = new List<OrderCardCreateEditModuleVM>();
                    var unSelectedModuleTypes = new List<int>();
                    // var selectedModuleTypes = orderCardVM.ModulesVM
                    //     .Where(x => x.Addresses.Any(a => a))
                    //     .ToList();
                    foreach (var moduleAddresses in orderCardVM.ModulesVM)
                    {

Cursa/Views/Modules/Create.cshtml
@model DataLayer.Entities.Module

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

@* <h4>Module</h4> *@
@* <hr /> *@
@* <div class="row"> *@
@*     <div class="col-md-4"> *@
@*         <form asp-action="Create"> *@
@*             <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
@*             <div class="form-group"> *@
@*                 <label asp-for="ModuleTypeId" class="control-label"></label> *@
@*                 <select asp-for="ModuleTypeId" class ="form-control" asp-items="ViewBag.ModuleTypeId"></select> *@
@*             </div> *@
@*             <div class="form-group"> *@
@*                 <label asp-for="DestinationOrderCardId" class="control-label"></label> *@
@*                 <select asp-for="DestinationOrderCardId" class ="form-control" asp-items="ViewBag.DestinationOrderCardId"></select> *@
@*             </div> *@
@*             <div class="form-group"> *@
@*                 <label asp-for="SerialNumber" class="control-label"></label> *@
@*                 <input asp-for="SerialNumber" class="form-control" /> *@
@*                 <span asp-validation-for="SerialNumber" class="text-danger"></span> *@
@*             </div> *@
@*             <div class="form-group"> *@
@*                 <label asp-for="Place" class="control-label"></label> *@
@*                 <input asp-for="Place" class="form-control" /> *@
@*                 <span asp-validation-for="Place" class="text-danger"></span> *@
@*             </div> *@
@*             <div class="form-group"> *@
@*                 <label asp-for="ActualOrderCardId" class="control-label"></label> *@
@*                 <select asp-for="ActualOrderCardId" class ="form-control" asp-items="ViewBag.ActualOrderCardId"></select> *@
@*             </div> *@
@*             <div class="form-group"> *@
@*                 <label asp-for="ManufacturingData" class="control-label"></label> *@
@*                 <input asp-for="ManufacturingData" class="form-control" /> *@
@*                 <span asp-validation-for="ManufacturingData" class="text-danger"></span> *@
@*             </div> *@
@*             <div class="form-group"> *@
@*                             <label asp-for="FirmwareVersion" class="control-label"></label> *@
@*                             <input asp-for="FirmwareVersion" class="form-control" /> *@
@*                             <span asp-validation-for="FirmwareVersion" class="text-danger"></span></div> *@
@*            <div class="form-group"> *@
@*                            <label asp-for="EmployeeId" class="control-label"></label> *@
@*                            <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select> *@
@*                        </div> *@
@*             <div class="form-group"> *@
@*                 <input type="submit" value="Create" class="btn btn-primary" /> *@
@*             </div> *@
@*         </form> *@
@*     </div> *@
@* </div> *@
@* *@
@* <div> *@
@*     <a asp-action="GetModulesForCardOrder" asp-route-cardOrderId="@Model.DestinationOrderCardId">Назад</a> *@
@* </div> *@
@* @section Scripts { *@
@*     @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} *@
@* } *@

Cursa/Views/Modules/Delete.cshtml
@model DataLayer.Entities.Module

@{
    ViewData["Title"] = "Delete";
}

@{
    ViewData["Title"] = "Удаление карты заказа";
}

<h4>@ViewData["Title"]</h4>

<h6 style="color:red">Подтвердите удаление</h6>
<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModuleType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModuleType.Code)
        </dd >
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationOrderCard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinationOrderCard.Name)
        </dd >
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationPlace)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinationPlace)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirmwareVersion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirmwareVersion)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.GetFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ActualOrderCard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ActualOrderCard.Name)
        </dd >
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturingData)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturingData)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedUser.GetFullName)
        </dd >
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedUser.GetFullName)
        </dd >
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Удалить" class="btn btn-danger"/> |
        <a asp-action="GetModulesForCardOrder" asp-route-cardOrderId="@Model.DestinationOrderCardId">Назад</a>
    </form>
</div>

Cursa/Views/Modules/Details.cshtml
@model DataLayer.Entities.Module

@{
    ViewData["Title"] = "О модуле";
}

<div>
    <h4>@ViewData["Title"]</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModuleType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModuleType.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationOrderCard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinationOrderCard.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationPlace)
        </dt>
        <dd class="col-sm-10">
           @{
               if (@Model.DestinationPlace != -1)
               {
                   @Html.DisplayFor(model => model.DestinationPlace)
               }else
               {
                   <span>LPBS</span>
               }
           }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ActualOrderCard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ActualOrderCard.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturingData)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturingData)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirmwareVersion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirmwareVersion)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.GetFullName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedUser.GetFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedUser.GetFullName)
        </dd>
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> | *@
    @* <a asp-action="GetModulesForCardOrder" asp-route-cardOrderId="@Model.DestinationOrderCardId">Назад</a> *@
    <a href="/Modules/GetModulesForCardOrder?cardOrderId=@Model.DestinationOrderCardId">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
        </svg>
    </a>&nbsp; &nbsp; &nbsp;
    <a href="/Modules/Edit?id=@Model.Id">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            \n' +
            // ' <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>\n' +
            // '
        </svg>
    </a>&nbsp; &nbsp; &nbsp;
    <a href="/Modules/Delete?id=@Model.Id">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
    </a>
</div>

Cursa/Views/Modules/GetModulesForCardOrder.cshtml
@model Cursa.ViewModels.ModuleVM.ModuleDisplayViewModel

@{
    ViewData["Title"] = "Модули для карты заказа: ";
}

<h4>@ViewData["Title"] @Model.DestinationOrderCardName (№: @Model.DestinationOrderCardNumber)</h4>

<p>
    @* <a asp-action="Create" asp-route-subProjectId=""> *@
    @*         <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16"> *@
    @*             <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/> *@
    @*         </svg>Добавить [НЕАКТИВНАЯ ССЫЛКА] *@
    @*     </a> *@
</p>
<table id="modulesDatatable" class="table">
    <thead>
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ModuleType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActualOrderCardId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManufacturingData)
        </th>
        <th></th>
    </tr>
    </thead>
</table>

<div>
    <a asp-controller="OrderCards" asp-action="GetOrderCardsForProduct" asp-route-productId="@Model.ProductId">Назад</a>
</div>
@section Scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/moment.js/moment.js"></script>
    <script src="~/js/modulesDatatable.js"></script>
}
<script>
        let orderId=@Model.DestinationOrderCardId;
</script>



<style>
     
        th, td { white-space: nowrap; }
    .in_progress {
        background-color: #20c99750;
    }
    span.empty{
     text-align: center;
    font-size: 70%;
    color: red;
    }
    
        span.lpbs{
                    text-align: center;
                       font-weight: bold;
                        color: green;
                        }
</style>

Cursa/Views/Modules/Index.cshtml
@model IEnumerable<DataLayer.Entities.Module>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    @* <a asp-action="Create">Create New</a> *@
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModuleType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DestinationOrderCard)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DestinationPlace)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualOrderCard)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufacturingData)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleType.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DestinationOrderCard.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DestinationPlace)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualOrderCard.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufacturingData)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>